---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    iam.gke.io/gcp-service-account: grafana-datasource@wine-library-mate.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: gke.gcr.io/prometheus-engine/frontend:v0.18.1-gke.2
          args:
            - --web.listen-address=:9090
            - --query.project-id=wine-library-mate
          ports:
            - name: web
              containerPort: 9090
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: web
      port: 9090
      targetPort: web
