apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wine-db
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:17.10

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    size: 5Gi

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  bootstrap:
    initdb:
      database: wine_library
      owner: wine_app
      secret:
        name: wine-db-app
