apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev

images:
  - name: ghcr.io/wine-library/backend
    newTag: dev

configMapGenerator:
  - name: wine-app-config
    behavior: merge
    literals:
      - LIQUIBASE_CONTEXTS=dev
      - FRONTEND_URL=https://dev.wine-library.xyz

patches:
  - target:
      kind: Cluster
      name: wine-db
    patch: |
      - op: replace
        path: /spec/instances
        value: 1
      - op: replace
        path: /spec/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/resources/requests/memory
        value: 256Mi
  - target:
      kind: Deployment
      name: wine-app
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 320Mi
  - target:
      kind: Ingress
      name: wine
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.wine-library.xyz
      - op: replace
        path: /spec/rules/0/host
        value: dev.wine-library.xyz
