name: Deploy dev

run-name: deploy dev - ${{ github.actor }} - ${{ github.event_name }}

on:
  workflow_dispatch:
  push:
    branches: [ development ]
    paths: [ 'k8s/**' ]
  repository_dispatch:
    types: [ backend-image-published ]

concurrency:
  group: deploy-dev
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      namespace: dev
    secrets: inherit