apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

components:
  - ../../components/metabase
  - ../../components/frontend

labels:
  - pairs:
      environment: staging

images:
  - name: ghcr.io/wine-library/backend
    newTag: staging
  - name: ghcr.io/wine-library/frontend
    newTag: staging

configMapGenerator:
  - name: wine-app-config
    behavior: merge
    literals:
      - LIQUIBASE_CONTEXTS=staging
      - FRONTEND_URL=https://staging.wine-library.xyz

patches:
  - target:
      kind: Ingress
      name: wine
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.wine-library.xyz
      - op: replace
        path: /spec/rules/0/host
        value: staging.wine-library.xyz
  - target:
      kind: Ingress
      name: metabase
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: bi.staging.wine-library.xyz
      - op: replace
        path: /spec/rules/0/host
        value: bi.staging.wine-library.xyz
